update NodeJs / ExpressJs Tutorial
HelioNetworks/heliohost-wiki pull request #26
Opened 2023-07-17 13:09 UTC by ilyaschicha

This update aims to provide a more user-friendly and comprehensive experience for readers following the tutorial. The changes have been thoroughly reviewed and tested to ensure accuracy. Your feedback and suggestions are welcome to further improve the tutorial's quality and usefulness.

2023-07-17 15:34 UTC, BaileyJM02 requested changes
Looks good so far, a few small changes

2023-07-17 15:34 UTC, BaileyJM02 commented on tutorials/node.js/express.js.md
> +* Node.js Version: At least 14.21.0 tho i highly recommend using the latest one 17.9.1
```suggestion
* Node.js Version: minimum 14.21.0, though it is recommend to use the latest available, currently 17.9.1.
```

2023-07-17 15:34 UTC, BaileyJM02 commented on tutorials/node.js/express.js.md
> +* Application Root: / (folder where you uploaded your next project, i recommend / )
```suggestion
* Application Root: `/` (This is the folder where you uploaded your project)
```

2023-07-17 15:34 UTC, BaileyJM02 commented on tutorials/node.js/express.js.md
> +* Application Startup File: app.js (file we created earlier)
```suggestion
* Application Startup File: `app.js` (The entry point of our app, use the file we created earlier)
```

2023-07-17 15:34 UTC, BaileyJM02 commented on tutorials/node.js/express.js.md
> +Once the Node.js application has been deployed you should be able to go to `domain.helioho.st/` and see the
```suggestion
Once the Node.js application has been deployed you should be able to go to the domain you selected and see the
```

2023-07-17 15:36 UTC, BaileyJM02 commented on tutorials/node.js/README.md
Could you revert the changes to this file? This is a useful bare-bones example of a NodeJS integration.

2023-07-17 22:16 UTC, ilyaschicha commented on tutorials/node.js/README.md
sure i will return it to it's original content one thing is when i used gitbook i found that you can access the folder Node.js without knowing that there is content inside it i realize that there is content inside only when Kryd0s send me the link for this repository

2023-07-18 10:31 UTC, ilyaschicha reviewed
i return it to it's original form but i update the images and add some images to the content

2023-07-22 21:36 UTC, Kryd0s commented
Thanks for the contribution.

2023-07-22 21:36 UTC, merged

2023-07-23 00:43 UTC, ilyaschicha commented
do you want me make tutorial of using Git in plesk @Kryd0s